name: MSBuild

on: [ push, pull_request ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Build
      run: |
        msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
        $cmdOutput = Split-Path -Path $pwd -Leaf
        echo "PROJECT_NAME=$cmdOutput" >> $Env:GITHUB_ENV

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.PROJECT_NAME }}
        path: |
          x64/${{env.BUILD_CONFIGURATION}}/*.exe
          x64/${{env.BUILD_CONFIGURATION}}/*.pdb
        if-no-files-found: error
